### ISSUE TITLE
Add a method to a keywords and meta tags to heads

### ISSUE THREAD

**Issue by Flexo013** [Flexo013/HeadsWebsite#14]
It would be nice if we could buff the search a little bit. Here's a few scenarios:
- A user searches "Medic"
- The user finds "Medic (Team Fortress 2)"
- A user searches "Team Fortress 2"
- The user finds "Medic (Team Fortress 2)"
- A user searches "TF2"
- The user does not find any heads

In this last scenario it is clear that the user wants to find Team Fortress 2 heads, but since the name does not contain TF2 the search will not return anything.

If we could add hidden key words to certain heads we could improve the search. We could for example make `pot` and `vase` return the almost the same search results.

What do you guys think about such an idea?

**Comment by Fancypants** [comment]
Added in the rename section. It will only show in the user collection lists next to headnames.

We have put a lot of thought into the database and even thought of tags since the beginning of the website, the site was only meant to come in handy for Mark to convert his heads into commands. However we weren't too sure how people would be using the database and didn't add this functionality. Long story short, the website was never meant to be what it is today: a large database with different methods to search the heads you are looking for. 

### Search methods

Categories - main collection
Headnames  - user collection (user collection has a copy of main collection)
Tags - user collection
Manual search through a list - both collections

### How does search work

When using the search in the user collection the engine first searches for Headnames, it does not need to be an exact match I.E. You have a database with `redstone, red flower, judge dredd`, a user searches for `red`; this will return all results! If a player searches `redstone` it will only find redstone. The same goes for tags, so try to keep the name simple but effective and go crazy in the tags.

Now this comes with a few changes:
- Only use easy-to-read headnames, `Poisin Ivy (batman series)` can now become `Poisin Ivy` with a `batman` tag.
- Try not to use too many tags, useless tags will clog up the search, tags are limited to 60 characters.
- Tags are separated through comma's I.E. `batman series,joker,clown` will lead to `batman series` `joker` and `clown`
- And a question, do we want users to (optionally) define tags for their heads?

**Comment by Flexo013** [comment]
Awesome.
Awesome!
AWESOME!
And yes I guess it would be nice if users could suggest tags. (If it happens to be nothing but extra work for moderation, then we can remove it again.)
